# SWE645 Assignment 2 - Kubernetes Deployment Configuration
# Authors: Divyanshi Detroja (G01522554), Yashwanth Katanguri (G01514418), Aditi Srivastava
# This file contains the Kubernetes deployment and service configuration for the student survey application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-app
  namespace: swe645-assignment
  labels:
    app: student-survey
spec:
  replicas: 3  # Minimum 3 pods as required by assignment
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: your-dockerhub-username/studentsurvey645:latest  # Replace with your DockerHub username
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: student-survey-service
  namespace: swe645-assignment
  labels:
    app: student-survey
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: student-survey
---
apiVersion: v1
kind: Namespace
metadata:
  name: swe645-assignment
  labels:
    name: swe645-assignment
