apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentsurvey-app
  labels:
    app: studentsurvey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studentsurvey
  template:
    metadata:
      labels:
        app: studentsurvey
    spec:
      containers:
      - name: studentsurvey
        image: divyanshidetroja/studentsurvey645:0.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
